apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: virtus-shop-apps
resources:
  - deployment.yaml
  - service.yaml
  - secret.yaml
images:
  - name: product-api-image
    newName: image-registry.openshift-image-registry.svc:5000/virtus-shop-apps/product-api
    newTag: ce480dffea3e7667b47085138a5f82284382e09a
