# DEMO ONLY — di production pakai SealedSecrets/External Secrets/Vault
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: vti-shop-apps
type: Opaque
stringData:
  DB_HOST: mysql.virtus-shop-db.svc.cluster.local
  DB_PORT: "3306"
  DB_USER: shop
  DB_PASS: shopPass123
  DB_NAME: virtusshop
