apiVersion: v1
kind: Service
metadata:
  name: product-api
  namespace: virtus-shop-apps
  labels:
    app: product-api
spec:
  selector:
    app: product-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
