apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: virtus-shop-apps
resources:
  - rollout.yaml
  - services.yaml
  - virtualservice.yaml
  - analysistemplate.yaml
images:
  - name: frontend-image
    newName: image-registry.openshift-image-registry.svc:5000/virtus-shop-apps/frontend
    newTag: 78cc8ff74055c64d468e8026c4e2b3b211716956
