apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: virtus-shop-apps
resources:
  - rollout.yaml
  - services.yaml
  - virtualservice.yaml
  - analysistemplate.yaml
images:
  - name: frontend-image
    newName: image-registry.openshift-image-registry.svc:5000/virtus-shop-apps/frontend
    newTag: b9f3d4a955eaf9a73d58d17bd009836dab5f3b45
