apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: virtus-shop-apps
resources:
  - rollout.yaml
  - services.yaml
  - virtualservice.yaml
  - analysistemplate.yaml
images:
  - name: frontend-image
    newName: image-registry.openshift-image-registry.svc:5000/virtus-shop-apps/frontend
    newTag: e72baf3f2d8df0807af1cbfd71482f24c769612a
