apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: virtus-shop-apps
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: shop-ui-image
    newName: image-registry.openshift-image-registry.svc:5000/virtus-shop-apps/shop-ui
    newTag: ee1cf62ceb989d757f79514783721dccd22601dc
