apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: virtus-shop-apps
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: shop-ui-image
    newName: image-registry.openshift-image-registry.svc:5000/virtus-shop-apps/shop-ui
    newTag: a755b25ddfcdac0428e0bc1cad5ea4ee8348f32b
