apiVersion: v1
kind: Service
metadata:
  name: shop-ui
  namespace: virtus-shop-apps
  labels:
    app: shop-ui
spec:
  selector:
    app: shop-ui
  ports:
    - name: http
      port: 8080
      targetPort: 8080
