apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vti-shop-apps
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: order-api-image
    newName: image-registry.openshift-image-registry.svc:5000/vti-shop-apps/order-api
    newTag: dfdc58f3fb609e905beaa19e96659f5117c1c02a
